#!/bin/sh
PARENT_DIR="$(dirname $(pwd))"
if [ -d "$PARENT_DIR/brower-extension" ];
then
    echo "WARNING: Please build the latest brower-extension first"

    mkdir -p extension
    rm -r ./extension/*
    mkdir -p dist
    rm -r ./dist/*
    cp -r ../brower-extension/build ./extension/;
    echo "Coppied /build/*";
    cp -r ../brower-extension/assert ./extension/;
    echo "Coppied /assert/*";
    cp -r ../brower-extension/manifest.json ./extension/;
    echo "Coppied /manifest.json";

    npm install;
    node ./_scripts/update_manifest.js;
    echo "Updated manifest.json";

    cd extension;
    find . \( -name '.DS_Store' -or -name '._*' \) -delete
    zip -r ../dist/voz-living.xpi *;
    echo "Compiled dist/voz-living.xpi";
    echo "Done! Please see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Packaging_and_installation for more information how to load the extension to firefox";
else
    echo "brower-extension need to be same level as firefox-extenions";
fi
